import os
from dotenv import load_dotenv

load_dotenv()

class Constant:
  SOURCE_DATA_LAKE= os.getenv("SOURCE_DATA_LAKE")
  SOURCE_AGENTS_SHEET_ID = os.getenv("SOURCE_AGENTS_SHEET_ID")
  SOURCE_AWS_ACCESS_KEY_ID=os.getenv("SOURCE_AWS_ACCESS_KEY_ID")
  SOURCE_AWS_SECRET_ACCESS_KEY=os.getenv("SOURCE_AWS_SECRET_ACCESS_KEY")

  WEBSITE_FORM_DB_NAME=os.getenv("WEBSITE_FORM_DB_NAME")
  WEBSITE_FORM_DB_HOST=os.getenv("WEBSITE_FORM_DB_HOST")
  WEBSITE_FORM_DB_PASSWORD=os.getenv("WEBSITE_FORM_DB_PASSWORD")
  WEBSITE_FORM_DB_USER=os.getenv("WEBSITE_FORM_DB_USER")
  WEBSITE_FORM_DB_SCHEMA=os.getenv("WEBSITE_FORM_DB_SCHEMA")

  DESTINATION_DATA_LAKE = os.getenv("DESTINATION_DATA_LAKE")
  DESTINATION_AWS_ACCESS_KEY_ID = os.getenv("DESTINATION_AWS_ACCESS_KEY_ID")
  DESTINATION_AWS_SECRET_ACCESS_KEY = os.getenv("DESTINATION_AWS_SECRET_ACCESS_KEY")

  GOOGLE_JSON_PATH = os.getenv("GOOGLE_CREDENTIALS_PATH", "google_secret.json")

  
