core_telecoms:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}" # Org-Account format
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "CORE_TELECOMS_WH"
      database: "CORE_TELECOMS"
      schema: "STAGING" # Default schema for runs
      threads: 4